-- URLs table
CREATE TABLE IF NOT EXISTS urls (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  original_url VARCHAR(2048) NOT NULL,
  short_url VARCHAR(16) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_short_url (short_url)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
-- URL hits for analytics
CREATE TABLE IF NOT EXISTS url_hits (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  url_id BIGINT NOT NULL,
  hit_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_agent VARCHAR(255) NOT NULL,
  ip VARCHAR(45) NOT NULL,
  referer VARCHAR(2048) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (url_id) REFERENCES urls(id),
  INDEX idx_url_hits (url_id, hit_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;